[package]

name = "mal"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]

[dependencies]
time = "0.1"
regex = "0.1"
libc = "0.1"

[dependencies.pcre]
git = "https://github.com/alexcrichton/rust-pcre"
